/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafamus
 */

import java.awt.*;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Reservations extends javax.swing.JFrame {

    /**
     * Creates new form Reservations
     */
    public Reservations() {
        initComponents();
        showReservations();
    }
    
    public ArrayList<ReserveData> reservationsList(){
        ArrayList<ReserveData> reservationsList = new ArrayList<>();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coworkingspacesreservation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root", "15264859");
            String query1 = "select * from reservations";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            ReserveData reservedata;
            while (rs.next()){
                reservedata = new ReserveData(rs.getInt("reservation_id"), rs.getString("customer_name"), rs.getString("roomOrtable"), rs.getString("item_id"), rs.getString("item_name"), rs.getString("startdate"), rs.getString("enddate"), rs.getString("price"), rs.getBoolean("paid"), rs.getBoolean("done"));
                reservationsList.add(reservedata);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return reservationsList;
    }
    
    public void showReservations(){
        ArrayList<ReserveData> list = reservationsList();
        DefaultTableModel reservationsTableModel = (DefaultTableModel)reservationsTable.getModel();
        reservationsTableModel.setRowCount(0);
        Object[] row = new Object[10];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getReservationID();
            row[1] = list.get(i).getCustomerName();
            row[2] = list.get(i).getRoomOrTable();
            row[3] = list.get(i).getItemID();
            row[4] = list.get(i).getItemName();
            row[5] = list.get(i).getStartDate();
            row[6] = list.get(i).getEndDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getPaid();
            row[9] = list.get(i).getDone();
            reservationsTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        reservationID = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        roomortable = new javax.swing.JTextField();
        itemName = new javax.swing.JTextField();
        fromwhen = new javax.swing.JTextField();
        towhen = new javax.swing.JTextField();
        pricereserve = new javax.swing.JTextField();
        addRoomTable = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        refreshRoomTable = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        searchReserve = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        backgroundBlue = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservations");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESERVATIONS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 0, 90, 30);

        reservationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation ID", "Customer Name", "Room/Table", "Item ID", "Item Name", "Start Date", "End Date", "Price", "Paid", "Done"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservationsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reservationsTable);
        if (reservationsTable.getColumnModel().getColumnCount() > 0) {
            reservationsTable.getColumnModel().getColumn(0).setResizable(false);
            reservationsTable.getColumnModel().getColumn(1).setResizable(false);
            reservationsTable.getColumnModel().getColumn(2).setResizable(false);
            reservationsTable.getColumnModel().getColumn(3).setResizable(false);
            reservationsTable.getColumnModel().getColumn(4).setResizable(false);
            reservationsTable.getColumnModel().getColumn(5).setResizable(false);
            reservationsTable.getColumnModel().getColumn(6).setResizable(false);
            reservationsTable.getColumnModel().getColumn(7).setResizable(false);
            reservationsTable.getColumnModel().getColumn(8).setResizable(false);
            reservationsTable.getColumnModel().getColumn(9).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 680, 180);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Item Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 250, 80, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reservation ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 90, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room/Table");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 200, 80, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("From");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 100, 50, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("To");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 150, 40, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 200, 50, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Customer Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 150, 100, 30);

        reservationID.setEditable(false);
        reservationID.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(reservationID);
        reservationID.setBounds(140, 100, 160, 30);

        customerName.setEditable(false);
        customerName.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(customerName);
        customerName.setBounds(140, 150, 160, 30);

        roomortable.setEditable(false);
        roomortable.setBackground(new java.awt.Color(204, 204, 204));
        roomortable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomortableActionPerformed(evt);
            }
        });
        getContentPane().add(roomortable);
        roomortable.setBounds(140, 200, 160, 30);

        itemName.setEditable(false);
        itemName.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(itemName);
        itemName.setBounds(140, 250, 160, 30);

        fromwhen.setEditable(false);
        fromwhen.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fromwhen);
        fromwhen.setBounds(420, 100, 250, 30);

        towhen.setEditable(false);
        towhen.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(towhen);
        towhen.setBounds(420, 150, 250, 30);

        pricereserve.setEditable(false);
        pricereserve.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(pricereserve);
        pricereserve.setBounds(420, 200, 250, 30);

        addRoomTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        addRoomTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-add-50.png"))); // NOI18N
        addRoomTable.setText("Add Reservation");
        addRoomTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addRoomTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addRoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomTableActionPerformed(evt);
            }
        });
        getContentPane().add(addRoomTable);
        addRoomTable.setBounds(260, 10, 130, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-back-arrow-40.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 30, 40, 50);

        refreshRoomTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        refreshRoomTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-check-all-50.png"))); // NOI18N
        refreshRoomTable.setText("Mark as Paid");
        refreshRoomTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshRoomTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshRoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRoomTableActionPerformed(evt);
            }
        });
        getContentPane().add(refreshRoomTable);
        refreshRoomTable.setBounds(410, 10, 130, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-close-window-30.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 0, 30, 30);

        searchReserve.setMinimumSize(new java.awt.Dimension(2, 20));
        searchReserve.setPreferredSize(new java.awt.Dimension(2, 20));
        searchReserve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchReserveKeyReleased(evt);
            }
        });
        getContentPane().add(searchReserve);
        searchReserve.setBounds(480, 250, 210, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Filter");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 260, 40, 14);

        backgroundBlue.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/adminb.jpg")).getImage().getScaledInstance(700, 500, Image.SCALE_SMOOTH)));
        getContentPane().add(backgroundBlue);
        backgroundBlue.setBounds(0, -20, 700, 500);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Minimize");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Shortcuts");

        jMenu3.setText("Rooms Details");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Add Room");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu2.add(jMenu3);

        jMenu4.setText("Tables Details");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Add Table");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        jMenu6.setText("Reservations");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Add Reservation");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roomortableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomortableActionPerformed

    }//GEN-LAST:event_roomortableActionPerformed

    private void addRoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomTableActionPerformed
        AddReservation addreservation = new AddReservation();
        addreservation.setVisible(true);
    }//GEN-LAST:event_addRoomTableActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        CloseMe();
        MainMenu mainmenu = new MainMenu();
        mainmenu.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        showReservations();
    }//GEN-LAST:event_formWindowGainedFocus

    private void refreshRoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRoomTableActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coworkingspacesreservation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root", "15264859");
            String reservationIDh = reservationID.getText();
            String update1 = "update reservations set paid = CASE WHEN paid = 0 THEN 1 WHEN paid = 1 THEN 0 END where reservation_id = '"+reservationIDh+"'";
            PreparedStatement pst = con.prepareStatement(update1);
            pst.execute();
            showReservations();
        }
        catch(Exception e){
            System.out.println("Select a row first!");
        }
    }//GEN-LAST:event_refreshRoomTableActionPerformed

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        jLabel9.setIcon(new javax.swing.ImageIcon("icons8-close-window-30-ConvertImage.png"));
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        CloseMe();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setIcon(new javax.swing.ImageIcon("icons8-close-window-30.png"));
    }//GEN-LAST:event_jLabel9MouseExited

    private void reservationsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsTableMouseClicked
        int i = reservationsTable.getSelectedRow();
        TableModel reservationTableModel = reservationsTable.getModel();
        reservationID.setText(reservationTableModel.getValueAt(i,0).toString());
        customerName.setText(reservationTableModel.getValueAt(i,1).toString());
        roomortable.setText(reservationTableModel.getValueAt(i,2).toString());
        itemName.setText(reservationTableModel.getValueAt(i,4).toString());
        String from = reservationTableModel.getValueAt(i,5).toString();
        String to = reservationTableModel.getValueAt(i,6).toString();
        from = charRemoveAt(from,1);
        fromwhen.setText(from);
        from = charRemoveAt(from,8);
        fromwhen.setText(from);
        from = charRemoveAt(from,8);
        fromwhen.setText(from);
        to = charRemoveAt(to,1);
        towhen.setText(to);
        to = charRemoveAt(to,8);
        towhen.setText(to);
        to = charRemoveAt(to,8);
        towhen.setText(to);
        pricereserve.setText(reservationTableModel.getValueAt(i,7).toString());
        String pricefinal = "₱" + pricereserve.getText();
        pricereserve.setText(pricefinal);
    }//GEN-LAST:event_reservationsTableMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CloseMe();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AddRoom addroom = new AddRoom();
        addroom.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AddTable addtable = new AddTable();
        addtable.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AddReservation addreservation = new AddReservation();
        addreservation.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void searchReserveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchReserveKeyReleased

        ArrayList<ReserveData> list = new ArrayList<ReserveData>();
        String searchQuery = searchReserve.getText();

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coworkingspacesreservation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root", "15264859");

            String searchCommand = "select * from reservations where reservation_id like '%"+searchQuery+"%' or customer_name like '%"+searchQuery+"%' or roomOrtable like '%"+searchQuery+"%' or item_id like '%"+searchQuery+"%' or item_name like '%"+searchQuery+"%' or startdate like '%"+searchQuery+"%' or enddate like '%"+searchQuery+"%' or price like '%"+searchQuery+"%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(searchCommand);
            ReserveData reservedata;
            while (rs.next()){
                reservedata = new ReserveData(rs.getInt("reservation_id"), rs.getString("customer_name"), rs.getString("roomOrtable"), rs.getString("item_id"), rs.getString("item_name"), rs.getString("startdate"), rs.getString("enddate"), rs.getString("price"), rs.getBoolean("paid"), rs.getBoolean("done"));
                list.add(reservedata);
            }
        }
        catch(Exception e){
            System.out.println("Type in search textfield to search");
        }
        DefaultTableModel reservationsTableModel = (DefaultTableModel)reservationsTable.getModel();
        reservationsTableModel.setRowCount(0);
        Object[] row = new Object[10];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getReservationID();
            row[1] = list.get(i).getCustomerName();
            row[2] = list.get(i).getRoomOrTable();
            row[3] = list.get(i).getItemID();
            row[4] = list.get(i).getItemName();
            row[5] = list.get(i).getStartDate();
            row[6] = list.get(i).getEndDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getPaid();
            row[9] = list.get(i).getDone();
            reservationsTableModel.addRow(row);
        }
    }//GEN-LAST:event_searchReserveKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservations().setVisible(true);
            }
        });
    }
    
    private void CloseMe(){
        WindowEvent meClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
    }
    
    public static String charRemoveAt(String str, int p) {  
              return str.substring(0, p) + str.substring(p + 1);
    } 
    
    public static String charRemoveAt1(String str, int p) {  
              return str.substring(0, p) + str.substring(p + 1);
    } 
    
    public static String charRemoveAt2(String str, int p) {  
              return str.substring(0, p) + str.substring(p + 1);
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomTable;
    private javax.swing.JLabel backgroundBlue;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField fromwhen;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pricereserve;
    private javax.swing.JButton refreshRoomTable;
    private javax.swing.JTextField reservationID;
    private javax.swing.JTable reservationsTable;
    private javax.swing.JTextField roomortable;
    private javax.swing.JTextField searchReserve;
    private javax.swing.JTextField towhen;
    // End of variables declaration//GEN-END:variables
}
