/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafamus
 */

import java.awt.*;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form RoomsAndTables
     */
    public Rooms() {
        initComponents();
        showRooms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        searchButtonGroupR = new javax.swing.ButtonGroup();
        refreshRoomTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomsTable = new javax.swing.JTable();
        roomID = new javax.swing.JTextField();
        roomLoc = new javax.swing.JTextField();
        roomName = new javax.swing.JTextField();
        roomPrice = new javax.swing.JTextField();
        addRoomTable = new javax.swing.JButton();
        deleteRoomTable = new javax.swing.JButton();
        editRoomTable = new javax.swing.JButton();
        searchRooms = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roomSize = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backgroundBlue = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rooms");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        refreshRoomTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        refreshRoomTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-refresh-50.png"))); // NOI18N
        refreshRoomTable.setText("Refresh");
        refreshRoomTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshRoomTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshRoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRoomTableActionPerformed(evt);
            }
        });
        getContentPane().add(refreshRoomTable);
        refreshRoomTable.setBounds(560, 30, 130, 80);

        roomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Name", "Location", "Room Size", "Price", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roomsTable);
        if (roomsTable.getColumnModel().getColumnCount() > 0) {
            roomsTable.getColumnModel().getColumn(0).setResizable(false);
            roomsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 310, 680, 160);

        roomID.setEditable(false);
        roomID.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(roomID);
        roomID.setBounds(150, 130, 140, 30);

        roomLoc.setEditable(false);
        roomLoc.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(roomLoc);
        roomLoc.setBounds(150, 230, 140, 30);

        roomName.setEditable(false);
        roomName.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(roomName);
        roomName.setBounds(150, 180, 140, 30);

        roomPrice.setEditable(false);
        roomPrice.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(roomPrice);
        roomPrice.setBounds(480, 180, 140, 30);

        addRoomTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        addRoomTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-add-50.png"))); // NOI18N
        addRoomTable.setText("Add an Item");
        addRoomTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addRoomTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addRoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomTableActionPerformed(evt);
            }
        });
        getContentPane().add(addRoomTable);
        addRoomTable.setBounds(110, 30, 130, 80);

        deleteRoomTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        deleteRoomTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-delete-bin-50.png"))); // NOI18N
        deleteRoomTable.setText("Archive Selected");
        deleteRoomTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteRoomTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteRoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomTableActionPerformed(evt);
            }
        });
        getContentPane().add(deleteRoomTable);
        deleteRoomTable.setBounds(260, 30, 130, 80);

        editRoomTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        editRoomTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-edit-50.png"))); // NOI18N
        editRoomTable.setText("Edit Info");
        editRoomTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editRoomTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editRoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoomTableActionPerformed(evt);
            }
        });
        getContentPane().add(editRoomTable);
        editRoomTable.setBounds(410, 30, 130, 80);

        searchRooms.setMinimumSize(new java.awt.Dimension(2, 20));
        searchRooms.setPreferredSize(new java.awt.Dimension(2, 20));
        searchRooms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchRoomsKeyReleased(evt);
            }
        });
        getContentPane().add(searchRooms);
        searchRooms.setBounds(480, 270, 210, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROOMS DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 0, 130, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 70, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 90, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Location");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 230, 70, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 180, 50, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-back-arrow-40.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 30, 40, 50);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Size");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 130, 40, 30);

        roomSize.setEditable(false);
        roomSize.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(roomSize);
        roomSize.setBounds(480, 130, 140, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/icons8-close-window-30.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 0, 30, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Filter");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 280, 40, 14);

        backgroundBlue.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/coworkingspacesreservation/adminb.jpg")).getImage().getScaledInstance(700, 500, Image.SCALE_SMOOTH)));
        getContentPane().add(backgroundBlue);
        backgroundBlue.setBounds(0, 0, 700, 500);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Minimize");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Shortcuts");

        jMenu3.setText("Rooms Details");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Add Room");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu2.add(jMenu3);

        jMenu4.setText("Tables Details");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Add Table");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        jMenu6.setText("Reservations");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Add Reservation");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(716, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<RoomData> roomsList(){
        ArrayList<RoomData> roomsList = new ArrayList<>();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coworkingspacesreservation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root", "15264859");
            String query1 = "select * from rooms";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            RoomData roomdata;
            while (rs.next()){
                roomdata = new RoomData(rs.getInt("room_id"), rs.getString("room_name"), rs.getString("room_location"), rs.getString("room_size"), rs.getString("room_price"), rs.getBoolean("available"));
                roomsList.add(roomdata);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return roomsList;
    }
    
    public void showRooms(){
        ArrayList<RoomData> list = roomsList();
        DefaultTableModel roomTableModel = (DefaultTableModel)roomsTable.getModel();
        roomTableModel.setRowCount(0);
        Object[] row = new Object[6];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getRoomID();
            row[1] = list.get(i).getRoomName();
            row[2] = list.get(i).getRoomLocation();
            row[3] = list.get(i).getRoomSize();
            row[4] = list.get(i).getRoomPrice();
            row[5] = list.get(i).getavailable();
            roomTableModel.addRow(row);
        }
    }
        
    
    private void refreshRoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRoomTableActionPerformed
        showRooms();
    }//GEN-LAST:event_refreshRoomTableActionPerformed

    private void addRoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomTableActionPerformed
        AddRoom addroomtable = new AddRoom();
        addroomtable.setVisible(true);
    }//GEN-LAST:event_addRoomTableActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        CloseMe();
        MainMenu mainmenu = new MainMenu();
        mainmenu.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void editRoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoomTableActionPerformed
        try{
        EditRoomDetails editroomdetails = new EditRoomDetails();
        int index = roomsTable.getSelectedRow();
        TableModel roomTableModel = roomsTable.getModel();
        String roomID = roomTableModel.getValueAt(index, 0).toString();
        String roomName = roomTableModel.getValueAt(index, 1).toString();
        String roomLocation = roomTableModel.getValueAt(index, 2).toString();
        String roomSize = roomTableModel.getValueAt(index, 3).toString();
        String roomPrice = roomTableModel.getValueAt(index, 4).toString();
        editroomdetails.setVisible(true);
        editroomdetails.updateRoomID.setText(roomID);
        editroomdetails.updateRoomName.setText(roomName);
        editroomdetails.updateRoomLocation.setText(roomLocation);
        editroomdetails.updateRoomSize.setText(roomSize);
        editroomdetails.updateRoomPrice.setText(roomPrice);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Select a row to update first!");
        }
    }//GEN-LAST:event_editRoomTableActionPerformed

    private void roomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsTableMouseClicked
        int i = roomsTable.getSelectedRow();
        TableModel roomTableModel = roomsTable.getModel();
        roomID.setText(roomTableModel.getValueAt(i,0).toString());
        roomName.setText(roomTableModel.getValueAt(i,1).toString());
        roomLoc.setText(roomTableModel.getValueAt(i,2).toString());
        roomSize.setText(roomTableModel.getValueAt(i,3).toString());
        roomPrice.setText(roomTableModel.getValueAt(i,4).toString());
    }//GEN-LAST:event_roomsTableMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        showRooms();
    }//GEN-LAST:event_formWindowGainedFocus

    private void deleteRoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomTableActionPerformed
        try{
            if (!("".equals(roomID.getText()))){
            int confirm = JOptionPane.showConfirmDialog(roomsTable, "Are you sure you want to delete room " + roomName.getText() + " from your database?", "Delete Room", JOptionPane.OK_CANCEL_OPTION);
                if (confirm == JOptionPane.YES_OPTION){
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coworkingspacesreservation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root", "15264859");
                    String idRoom = roomID.getText();
                    String query2 = "delete from rooms where room_id = '"+idRoom+"'";
                    PreparedStatement pst = con.prepareStatement(query2);
                    pst.execute();
                    showRooms();
                }
            }
            else{
                System.out.println("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Select a row to delete first!");
        }
    }//GEN-LAST:event_deleteRoomTableActionPerformed

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        jLabel9.setIcon(new javax.swing.ImageIcon("icons8-close-window-30-ConvertImage.png"));
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        CloseMe();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setIcon(new javax.swing.ImageIcon("icons8-close-window-30.png"));
    }//GEN-LAST:event_jLabel9MouseExited

    private void searchRoomsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchRoomsKeyReleased

        ArrayList<RoomData> list = new ArrayList<RoomData>();
        String searchQuery = searchRooms.getText();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/coworkingspacesreservation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root", "15264859");
            
                String searchCommand = "select * from rooms where room_id like '%"+searchQuery+"%' or room_name like '%"+searchQuery+"%' or room_location like '%"+searchQuery+"%' or room_size like '%"+searchQuery+"%' or room_price like '%"+searchQuery+"%'";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(searchCommand);
                RoomData roomdata;
                while (rs.next()){
                    roomdata = new RoomData(rs.getInt("room_id"), rs.getString("room_name"), rs.getString("room_location"), rs.getString("room_size"), rs.getString("room_price"), rs.getBoolean("available"));
                    list.add(roomdata);
                }
        }
        catch(Exception e){
            System.out.println("Type in search textfield to search");
        }
        DefaultTableModel roomTableModel = (DefaultTableModel)roomsTable.getModel();
        roomTableModel.setRowCount(0);
        Object[] row = new Object[6];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getRoomID();
            row[1] = list.get(i).getRoomName();
            row[2] = list.get(i).getRoomLocation();
            row[3] = list.get(i).getRoomSize();
            row[4] = list.get(i).getRoomPrice();
            row[5] = list.get(i).getavailable();
            roomTableModel.addRow(row);
        }
    }//GEN-LAST:event_searchRoomsKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CloseMe();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AddRoom addroom = new AddRoom();
        addroom.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AddTable addtable = new AddTable();
        addtable.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AddReservation addreservation = new AddReservation();
        addreservation.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }
    
    private void CloseMe(){
        WindowEvent meClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomTable;
    private javax.swing.JLabel backgroundBlue;
    private javax.swing.JButton deleteRoomTable;
    private javax.swing.JButton editRoomTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton refreshRoomTable;
    private javax.swing.JTextField roomID;
    private javax.swing.JTextField roomLoc;
    private javax.swing.JTextField roomName;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JTextField roomSize;
    private javax.swing.JTable roomsTable;
    private javax.swing.ButtonGroup searchButtonGroupR;
    private javax.swing.JTextField searchRooms;
    // End of variables declaration//GEN-END:variables
}
